p8105_hw1_my2838
================
Mia Yu
2023-09-18

# Problem 1

### Read and describe the dataset

``` r
data("early_january_weather")
nrow(early_january_weather) # calculate the rows
```

    ## [1] 358

``` r
ncol(early_january_weather) # calculate the columns 
```

    ## [1] 15

``` r
mean (early_january_weather$temp) # calculate the mean temperature
```

    ## [1] 39.58212

1.  The variables of the dataset are day, hour, temp, dewp, humid,
    wind_dir, wind_speed, wind_gust, precip, pressure, visib, time_hour.
    Generally, the weather data are measured from EWR, from of January 1
    to January 15, 2013.

2.  There are 358 rows and 15 columns in the dataset.

3.  The mean temperature is 39.58212.

### Make a scatterplot and describe patterns

``` r
ggplot(early_january_weather, aes(x = time_hour, y = temp, color = humid)) + geom_point() # creat the scatterplot
```

![](p8105_hw1_my2838_files/figure-gfm/unnamed-chunk-2-1.png)<!-- -->

``` r
ggsave("P8105_hw1_my2838_1.pdf") # save the plot
```

    ## Saving 7 x 5 in image

The plot shows that the temperature is generally rising from Jan 1 to
Jan 15, and also the percentage of humidity increased during that time
period.

# Problem 2

### Creat the data frame

``` r
problem2_df = tibble(
  vec_sample = rnorm(10),
  vec_logical = vec_sample > 0,
  vec_character = c("A","B","C","D","E","F","G","H","I","J"),
  vec_factor = factor(rep(c("a","b","c"), times = c(1,3,6))
)
)
```

### Calculate the mean value of each orginal variable

``` r
mean(pull(problem2_df, vec_sample))
```

    ## [1] 0.1536956

``` r
mean(pull(problem2_df, vec_logical))
```

    ## [1] 0.6

``` r
mean(pull(problem2_df, vec_character))
```

    ## Warning in mean.default(pull(problem2_df, vec_character)): argument is not
    ## numeric or logical: returning NA

    ## [1] NA

``` r
mean(pull(problem2_df, vec_factor))
```

    ## Warning in mean.default(pull(problem2_df, vec_factor)): argument is not numeric
    ## or logical: returning NA

    ## [1] NA

It *works* when calculating the mean of vec_sample and vec_logical. But
it *doesn’t work* when calculating the mean of vec_character and
vec_factor.

### Try `as.numeric` function

``` r
mean(as.numeric(pull(problem2_df,vec_logical)))
```

    ## [1] 0.6

``` r
mean(as.numeric(pull(problem2_df,vec_character)))
```

    ## Warning in mean(as.numeric(pull(problem2_df, vec_character))): NAs introduced
    ## by coercion

    ## [1] NA

``` r
mean(as.numeric(pull(problem2_df,vec_factor)))
```

    ## [1] 2.5

R reads TRUE as 1 and FALSE as 0. When as.numeric() function is applied
to logical variable, the logical value will contain the numerical values
of 0 and 1.

It is not possible to find the mean of a character variable. When
as.numeric() function is applied to characters, R cannot identified the
character data type into numeric data type and so the result is NA.

It is not possible to find the mean of a factor variable. When
as.numeric() function is applied to factors, R identified each level in
numerical values of 1, 2, 3.
